#!/usr/bin/env bash
# Build the documentation site from wiki/ without modifying it.
#
# wiki/ stays byte-identical so scripts/push_wiki.sh keeps syncing the
# GitHub wiki. The site builds from a prepared copy:
#   - every wiki/*.md page is copied into site-src/
#   - wiki/00-Home.md is also copied as site-src/index.md (the landing page)
#   - mkdocs.yml excludes the wiki-only files from the build
#
# Usage:
#   bash scripts/build_site.sh          # build into site/
# Then open site/index.html, or let CI deploy it to GitHub Pages.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

rm -rf site-src
mkdir -p site-src
cp wiki/*.md site-src/
cp wiki/00-Home.md site-src/index.md
# The social preview card, served at /og-card.png so mkdocs.yml's og:image
# URL resolves on the domain. Generated by scripts/build_infographics.py.
cp assets/og-card.png site-src/og-card.png

# First-party copies of the infographics. wiki/ embeds them as
# raw.githubusercontent.com URLs (the form check_wiki.py enforces);
# scripts/site_hook.py rewrites those embeds to these copies at build
# time. Same origin as the page — no third-party DNS+TLS hop for what
# is usually the largest thing on the page, and edge-cached for far
# longer than the five minutes raw.githubusercontent.com allows.
mkdir -p site-src/assets
cp assets/*.png site-src/assets/
rm -f site-src/assets/og-card.png

# The Bongwe theme (bongwe.space's design language). mkdocs.yml references
# it via extra_css; it lives in site-theme/ because site-src/ is generated.
mkdir -p site-src/assets/stylesheets
cp site-theme/bongwe.css site-src/assets/stylesheets/bongwe.css

# robots.txt: without one, Cloudflare synthesizes a content-signals stub
# that has no Sitemap line — and that line is the one thing crawlers
# actually read here. Cloudflare still appends its signals block on the
# fly; this file only adds the pointer.
printf 'Sitemap: https://vibe.bongwe.space/sitemap.xml\n' > site-src/robots.txt

# llms.txt: a good share of this wiki's readers are AI agents fetching
# pages on someone's behalf. Give them a one-file index of every lesson,
# in the format they read first (https://llmstxt.org).
python3 scripts/gen_llms_txt.py > site-src/llms.txt

# --strict: an unresolved link or missing anchor fails the build rather than
# printing an INFO line nobody reads (the levels are set in mkdocs.yml).
mkdocs build --strict

# Then check the output: MkDocs validates source links, this validates that
# every link it actually wrote resolves. It is the gate that would have caught
# scripts/site_hook.py leaving all 828 internal links unrewritten.
python3 scripts/check_site.py site

echo "site built -> site/index.html"
